urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.event_brief, name='event_brief'),
    url(r'^prov/$', views.event_list, name='event_list'),
    url(r'^event/(?P<pk>\d+)$', views.event_detail, name='event_detail'),
    url(r'^export/$', views.event_details_list, name='event_details_list'),
    url(r'^regulars/$', views.regulars_list, name='regulars_list'),
    url(r'^edit/(?P<pk>\d+)$', views.event_edit, name='event_edit'),
    url(r'^del/(?P<pk>\d+)$', views.event_delete, name='event_delete'),
]

models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

class Event(models.Model):
    
    # Event Details
    title = models.CharField('title', max_length=255, default='')
    details = models.TextField('details', blank=True, default='', null=True)
    featured_img = models.ImageField(upload_to = 'uploads/', blank = True, help_text = "600 * 800 pixel image.")
    space = models.CharField('space', max_length=255, default="Hall") # convert to drop-down list
    is_public = models.BooleanField('public?', default=True)
    
    # Date / timings
    start_date = models.DateField('start date')
    end_date = models.DateField('end date', blank=True, null=True)
    getin_time = models.TimeField('get-in time', blank=True, null=True)
    setup_time = models.TimeField('set-up time', blank=True, null=True)
    open_time = models.TimeField('opening time', default='20:00:00')
    end_time = models.TimeField('closing time', default='00:00:00')
    is_weekly = models.BooleanField('weekly event?', default=False)

    # Pricing
    adv_price = models.DecimalField('advance price', max_digits=5, decimal_places=2, blank=True, null=True)
    door_price = models.DecimalField('door price', max_digits=5, decimal_places=2, blank=True, null=True)
    conc_price = models.DecimalField('concession price', max_digits=5, decimal_places=2, blank=True, null=True)
    ticket_link = models.CharField('ticket link', max_length=255, blank=True, null=True)
    
    # Charges
    total_fee = models.DecimalField('TOTAL fee', max_digits=5, decimal_places=2, blank=True, null=True)
    percentage = models.IntegerField('percentage of door', blank=True, null=True)
    deposit = models.DecimalField('advance fee', max_digits=5, decimal_places=2, blank=True, null=True)
    balance_due = models.DecimalField('balance due', max_digits=5, decimal_places=2, blank=True, null=True)
    deposit_date = models.DateField('deposit received', blank=True, null=True)
    balance_date = models.DateField('balance due date', blank=True, null=True)
    
    # Hirer contact details
    hirer_name = models.CharField('contact', max_length=255, blank=True, null=True)
    hirer_address = models.CharField('address', max_length=255, blank=True, null=True)
    hirer_postcode = models.CharField('postcode', max_length=255, blank=True, null=True)
    hirer_email = models.CharField('email', max_length=255, blank=True, null=True)
    hirer_phone = models.CharField('phone', max_length=255, blank=True, null=True)
    hirer_mobile = models.CharField('mobile', max_length=255, blank=True, null=True)
    
    # Housekeeping
    event_slug = models.SlugField (max_length=52, verbose_name="URL slug", help_text = 'URL friendly name; lowercase, numbers and underscores only.', blank=True, null=True)
    date_created = models.DateTimeField('date created', default=timezone.now)
    date_updated = models.DateTimeField('date updated', blank=True, null=True)
    owner = models.ForeignKey(User, verbose_name='owner',
        related_name='events', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'event'
        verbose_name_plural = 'events'
        ordering = ['start_date']

    def publish(self):
        self.date_updated = timezone.now()
        self.save()

    def __str__(self):
        return self.title

forms.py
#! /usr/bin/env python3
# -*- coding: UTF8 -*-

"""Host/diary - forms.py

Event Organiser
"""

__version__ = 0.1
__maintainer__ = "tim@assemblyrooms.org.uk"

# Modules

from django import forms

from .models import Event

time_choices = [
    ('None', '---'),
    ('08:00:00', '8am'),
    ('08:30:00', '8.30am'),
    ('09:00:00', '9am'),
    ('09:30:00', '9.30am'),
    ('10:00:00', '10am'),
    ('10:00:00', '10.30am'),
    ('11:00:00', '11am'),
    ('11:00:00', '11.30am'),
    ('12:00:00', 'midday'),
    ('12:00:00', '12.30'),
    ('13:00:00', '1pm'),
    ('13:00:00', '1.30pm'),
    ('14:00:00', '2pm'),
    ('14:00:00', '2.30pm'),
    ('15:00:00', '3pm'),
    ('15:00:00', '3.30pm'),
    ('16:00:00', '4pm'),
    ('16:00:00', '4.30pm'),
    ('17:00:00', '5pm'),
    ('17:00:00', '5.30pm'),
    ('18:00:00', '6pm'),
    ('18:00:00', '6.30pm'),
    ('19:00:00', '7pm'),
    ('19:00:00', '7.30pm'),
    ('20:00:00', '8pm'),
    ('20:00:00', '8.30pm'),
    ('21:00:00', '9pm'),
    ('21:00:00', '9.30pm'),
    ('22:00:00', '10pm'),
    ('22:00:00', '10.30pm'),
    ('23:00:00', '11pm'),
    ('23:00:00', '11.30pm'),
    ('00:00:00', 'midnight')
]

class EventEditForm(forms.ModelForm):
    
    class Meta:
        model = Event
        fields = (
                'title',
                'details',
                'featured_img',
                'space',
                'is_public',
                'start_date',
                'end_date',
                'getin_time',
                'setup_time',
                'open_time',
                'end_time',
                'is_weekly',
                'adv_price',
                'door_price',
                'conc_price',
                'ticket_link',
                'total_fee',
                'deposit',
                'balance_due',
                'deposit_date',
                'balance_date',
                'hirer_name',
                'hirer_address',
                'hirer_postcode',
                'hirer_email',
                'hirer_phone',
                'hirer_mobile',
                'event_slug',
                'date_created',
                'date_updated',
                'owner'
        )
        widgets = {
                'start_date': forms.SelectDateWidget(),
                'end_date': forms.SelectDateWidget(),
                'balance_date': forms.SelectDateWidget(),
                'deposit_date': forms.SelectDateWidget(),
                'open_time': forms.Select(choices=time_choices),
                'getin_time': forms.Select(choices=time_choices),
                'setup_time': forms.Select(choices=time_choices),
                'end_time': forms.Select(choices=time_choices),
        }

views.py
from django.shortcuts import render
from django.utils import timezone
from django.shortcuts import get_object_or_404

from .models import Event
from .forms import EventEditForm
from .decorators import user_is_author, user_is_creator

def event_list(request):
    events = Event.objects.filter(start_date__gte=timezone.now()).order_by('start_date')
    return render(request, 'diary/event_list.html', {'events': events})

def event_brief(request):
    events = Event.objects.filter(start_date__gte=timezone.now()).order_by('start_date')
    return render(request, 'diary/event_brief.html', {'events': events})

def event_detail(request, pk):
    event=get_object_or_404(Event, pk=pk)
    return render(request, 'diary/event_detail.html', {'event':event,})

def event_details_list(request):
    events = Event.objects.filter(is_weekly=False).filter(start_date__gte=timezone.now()).order_by('start_date')
    return render(request, 'diary/event_details_list.html', {'events': events})

def regulars_list(request):
    events = Event.objects.filter(is_weekly=True)
    return render(request, 'diary/event_details_list.html', {'events': events})

@user_is_creator
def event_edit(request, pk):
    event = get_object_or_404(Event, pk=pk)
    if request.method == "POST":
        form = EventEditForm(request.POST, request.FILES, instance=event)
        if form.is_valid():
            event = form.save(commit=False)
            event.owner = request.user
            event.save()
            return redirect('event_view', pk=event.pk)
    else:
        form = EventEditForm(instance=event)
    return render(request, 'diary/event_edit.html', {'form': form, 'event':event})

@user_is_creator
def event_delete(request, *args, **kwargs):
    event = get_object_or_404(Event, pk=kwargs['pk'])

    if request.method == "POST":
        # Delete the event
        r_del = event.delete()
    
        #Return to Event list
        new_event = neweventForm()
        new_player = UserCreationForm()
        events = event.objects.filter(created_date__lte=timezone.now()).order_by('created_date')
        return redirect('/')

    # Show Confirmation dialog
    return render(request, 'diary/event_delete.html', {'event':event})

templates/diary/arch.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
		"http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Assembly Rooms Intranet</title>
    <link rel="stylesheet" type="text/css" href="{% static 'diary/internal.css' %}">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
    <header>
        <a href="/"><h1><img src="{% static 'diary/arlogo_white.png' %}">Assembly Rooms Diary</h1></a>
    </header>
    <nav>
	    <ul>
        {% if user.is_authenticated %}
            <li><img class="mark" src="/static/icons/stock_person.svg">{{ user.get_username }}
            <ul>
                <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
            </ul>
            </li>   
        {% else %}
            <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
        {% endif %}
		    <li><a href="/">Home</a></li>
		    <li><a href="/export">Publicity</a></li>
		    <li><a href="/regulars">Regulars</a></li>
		    <li><a href="/prov">All Possible</a></li>
	    </ul>
    </nav>    
    <div id="page_content">
	    {% block content %}
	    {% endblock %}
    </div>
</body>

templates/diary/event_brief.html
{% extends 'diary/arch.html' %}

{% block content %}
    <h2>Briefing</h2>
    
	{% for event in events %}
	    {% if event.is_public  and event.deposit_date %}
	    <div class="datetime">
            <p><span class="date">{{ event.start_date|date:"l j F Y" }}{% if event.end_date %} - {{ event.end_date|date:"l j F Y" }}{% endif %}</span><br />
            <b>{{ event.open_time }}</b> - {{ event.end_time }}<br />
            <span class='space'>{{ event.space }}</span>
            {% if event.is_weekly %}
                - Weekly
            {% endif %}
            </p>
        </div>
	    <div id="event_info">
            <a href="event/{{ event.pk }}"><h3 class="event_title">{{ event.title }}</h3></a>
            <p>{% if event.featured_img %}<img src="/media/{{ event.featured_img }}" class="listing border"/> {% endif %}{{ event.details|truncatewords:42 }}
            <br /><b>
            {% if event.door_price < 0 %}
                Free
            {% elif event.door_price == 0 %}
			    Magic Hat donations
		    {% elif event.door_price == None %}
			    
            {% else %}
			    £{{ event.door_price }}
		    {% endif %}</b> 
                {% if event.conc_price %}
                / {{ event.conc_price }}
                {% endif %}
                {% if event.adv_price %}
                Advance: £{{ event.adv_price }} from <a href="{{ event.ticket_link }}">{{ event.ticket_link }}</a>
                {% endif %}
            </p>
        </div>
        <hr />
        {% endif %}
	{% endfor %}
{% endblock %}

templates/diary/event_delete.html
{% extends 'diary/arch.html' %}

{% block content %}
        <div id="event_info">
            <p>{{ event.space }} <span class="date">{{ event.start_date }}</span> - {{ event.end_date }}
                {% if event.is_weekly %}
                    Weekly
                {% endif %}
            <b>{{ event.open_time }}</b> - {{ event.end_time }}
            </p>
            <h1 class="event_title">{{ event.title }}</h1>
            <img src="{{ event.featured_img }}" />
            <p>{{ event.details }}
            {% if not event.is_public %}
                Private event.
            {% endif %}</p>
        </div>
        <div id="price_info">
            {% if event.is_public %}
            <b>Door Price:</b> £{{ event.door_price }}<br />
            <b>Concs:</b> {{ event.conc_price }}<br />
            <b>Advance:</b> {{ event.adv_price }} from {{ event.ticket_link }}
            {% endif %}
        </div>
        <hr />
        <div id="setup_info">
            <p><b>Get In:</b> {{ event.getin_time }} <b>Set-up:</b> {{ event.setup_time }}</p>
        </div>
        <div id="hirer_info">
            <p><b>Hirer:</b> {{ event.hirer_name }}<br />
            {{ event.hirer_address }}<br />
            {{ event.hirer_postcode }}<br />
            {{ event.hirer_email }}<br />
            {{ event.hirer_phone }}
            {{ event.hirer_mobile }}
            </p>
        </div>
        <div id="fee_info">
            <p><b>TOTAL FEE:</b> {{ event.total_fee }}<br />
            <b>Deposit:</b> {{ event.deposit }} <b>Paid:</b> {{ event.deposit_date }}<br />
            <b>Balance:</b> {{ event.balance_due }} <b>Due:</b> {{ event.balance_date }}
            </p>
        </div>
        <hr />
        <div id="office_info">
            <p><b>Date booked:</b> {{ event.date_created }}
            {% if event.date_updated %}<b>Updated:</b> {{ event.date_updated }}{% endif %} by {{ event.owner }}
        </div>
{% endblock %}

templates/diary/event_detail.html
{% extends 'diary/arch.html' %}

{% block content %}
        <div id="event_info">
            <p><span class="date">{{ event.start_date|date:"l j F Y" }}{% if event.end_date %} - {{ event.end_date|date:"l j F Y" }}{% endif %}</span> 
                {% if event.is_weekly %}
                    Weekly
                {% endif %}<br />
            <b>{{ event.open_time }}</b> - {{ event.end_time }}
            @ <span class='space'>{{ event.space }}</span>
            </p>
            <h1 class="event_title">{{ event.title }}</h1>
            <p>{% if event.featured_img %}<img src="/media/{{ event.featured_img }}" /> {% endif %}{{ event.details }}
            {% if not event.is_public %}
                Private event.
            {% endif %}</p>
        </div>
        <div id="price_info">
            {% if event.is_public %}
            <b>Door Price:</b> 
            {% if event.door_price < 0 %}
                Free
            {% elif event.door_price == 0 %}
			    Magic Hat donations
		    {% elif event.door_price == None %}
			    -?-
            {% else %}
			    £{{ event.door_price }}
		    {% endif %} 
                {% if event.conc_price %}
                / {{ event.conc_price }}
                {% endif %}
                {% if event.adv_price %}
                <br /><b>Advance:</b> £{{ event.adv_price }} from <a href="{{ event.ticket_link }}">{{ event.ticket_link }}</a>
                {% endif %}
            {% endif %}
        </div>
        <hr />
        <div id="setup_info">
            <p>{% if event.getin_time %}<b>Get In:</b> {{ event.getin_time }}{% endif %}
            {% if event.setup_time %}<b>Set-up:</b> {{ event.setup_time }}{% endif %}</p>
        </div>
        <div id="hirer_info">
            <p><b>Hirer:</b> {% if event.hirer_name %}{{ event.hirer_name }}{% endif %}<br />
            {% if event.hirer_address %}{{ event.hirer_address }}{% endif %}<br />
            {% if event.hirer_postcode %}{{ event.hirer_postcode }}{% endif %}<br />
            {{ event.hirer_email }}<br />
            {% if event.hirer_phone %}{{ event.hirer_phone }}{% endif %}
            {% if event.hirer_mobile %}{{ event.hirer_mobile }}{% endif %}
            </p>
        </div>
        <div id="fee_info">
            <p><b>TOTAL FEE:</b> 
            {% if event.percentage %}
                {{ event.percentage }}% of door up to £{{ event.total_fee }}
            {% else %}
                £{{ event.total_fee }}
            {% endif %}<br />
            {% if event.deposit_date %}<b>Deposit:</b> £{{ event.deposit }} <b>Paid:</b> {{ event.deposit_date }}<br />{% endif %}
            {% if event.balance_date %}<b>Balance:</b> £{{ event.balance_due }} <b>Due:</b> {{ event.balance_date }}{% endif %}
            </p>
        </div>
        <hr />
        <div id="office_info">
            <p><b>Date booked:</b> {{ event.date_created }}
            {% if event.date_updated %}<b>Updated:</b> {{ event.date_updated }}{% endif %} by {{ event.owner }}
        </div>
{% endblock %}

templates/diary/event_details_list.html
{% extends 'diary/arch.html' %}

{% block content %}
    <h2>What's On</h2>
    
	{% for event in events %}
	    {% if event.is_public %}
	    <div id="event_info"{% if not event.deposit_date %}class="prov"{% endif %}>
            
            <p>{% if event.is_weekly %}Every {{ event.start_date|date:"l" }}
            {% else %}{% if not event.deposit_date %}*-{ {% endif %}<span class="date">{{ event.start_date|date:"l j F Y" }}{% if event.end_date %} - {{ event.end_date|date:"l j F Y" }}{% endif %}</span>  {% endif %}<br />
            <b>{{ event.open_time }}</b> - {{ event.end_time }}<br />
            <span class='space'>{{ event.space }}</span>
            {% if event.getin_time %}
            Get In: {{ event.getin_time }} 
            {% endif %}
            {% if event.setup_time %}
            Set-up: {{ event.setup_time }}
            {% endif %}
            </p>
            <a href="/event/{{ event.pk }}"><h3 {% if event.deposit_date %}class="event_title"
            {% else %}class="prov"
            {% endif %}">{{ event.title }}{% if not event.deposit_date %} }-* {% endif %}</h3></a>
            <p>{% if event.featured_img %}<img src="/media/{{ event.featured_img }}" width="230" class="border"/> {% endif %}{{ event.details }}
            </p>
        </div>
        <div id="price_info">
            {% if event.is_public %}
            <b>Door Price:</b> 
            {% if event.door_price < 0 %}
                Free
            {% elif event.door_price == 0 %}
			    Magic Hat donations
		    {% elif event.door_price == None %}
			    -?-
            {% else %}
			    £{{ event.door_price }}
		    {% endif %} 
                {% if event.conc_price %}
                / {{ event.conc_price }}
                {% endif %}
                {% if event.adv_price %}
                <br /><b>Advance:</b> £{{ event.adv_price }} from <a href="{{ event.ticket_link }}">{{ event.ticket_link }}</a>
                {% endif %}
            {% endif %}
        </div>
        <div id="hirer_info">
            <p><b>Contact:</b> <a href="mailto:{{ event.hirer_email }}">{{ event.hirer_email }}</a>
        </div>
        <hr />
        {% endif %}
	{% endfor %}
{% endblock %}

templates/diary/event_edit.html
{% extends 'diary/arch.html' %}

{% block content %}
        <form method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="align_right"><button type="submit" class="save button"><img class="mark" src="/static/icons/dialog-ok.svg">Save</button></div>
        <div id="event_info">
            <p><label for="id_title">Title:</label>{{ form.title }}<br />
            <label for="id_space">Space:</label> {{ form.space }}<br />
            <label for="id_start_date">Start date:</label> {{ form.start_date }} <label for="id_end_date">End date:</label>{{ form.end_date }}</p>
            <p><label for="id_is_weekly">Weekly?:</label> {{ form.is_weekly }} 
            <label for="id_is_public">Public?:</label> {{ form.is_public }}</p>
            <label for="id_featured_image">Image:</label>{{ form.featured_img }}
            <p><label for="id_details">Details:</label>{{ form.details }}</p>
        </div>
        <div id="price_info">
            
            <b><label for="id_door_price">Door Price:</label></b> £{{ form.door_price }}
            <b><label for="id_conc_price">Concs:</label></b> £{{ form.conc_price }}<br />
            <b><label for="id_adv_price">Advance:</label></b> £{{ form.adv_price }} <label for="id_ticket_link">Ticket link:</label>{{ form.ticket_link }}
            
        </div>
        <hr />
        <div id="setup_info">
            <p><label for="id_open_time">Doors open:</label> {{ form.open_time }} <label for="id_end_time">End time:</label> {{ form.end_time }}<br />
            <label for="id_getin_time">Get In:</label> {{ form.getin_time }} <label for="id_setup_time">Set-up:</label> {{ form.setup_time }}</p>
        </div>
        <div id="hirer_info">
            <p><label for="id_hirer_name">Hirer:</label> {{ form.hirer_name }}<br />
            <label for="id_hirer_address">Address:</label>{{ form.hirer_address }}<br />
            <label for="id_hirer_postcode">Postcode:</label>{{ form.hirer_postcode }}<br />
            <label for="id_hirer_email">Email:</label>{{ form.hirer_email }}<br />
            <label for="id_hirer_phone">Phone:</label>{{ form.hirer_phone }}
            <label for="id_hirer_mobile">Mobile:</label>{{ form.hirer_mobile }}
            </p>
        </div>
        <div id="fee_info">
            <p><label for="id_total_fee">TOTAL FEE:</label> £{{ form.total_fee }}<br />
            <label for="id_deposit">Deposit:</label> £{{ form.deposit }} <label for="id_deposit_date">Paid:</label> {{ form.deposit_date }}<br />
            <label for="id_balance_due">Balance:</label> £{{ form.balance_due }} <label for="id_balance_date">Due:</label> {{ form.balance_date }}
            </p>
        </div>
        <hr />
        <div id="office_info">
            <p><label for="id_date_created">Date booked:</label> {{ event.date_created }}
            {% if event.date_updated %}<label for="id_date_updated">Updated:</label> {{ event.date_updated }}{% endif %} by {{ form.owner }}
        </div>
    </form>
{% endblock %}

templates/diary/event_list.html
{% extends 'diary/arch.html' %}

{% block content %}
    <h2>Calendar</h2>
    <table>
	<caption>Forthcoming Events</caption>
	    <tr>
	        <th  valign="bottom"  align="left"><b>DATE</b></th>
	        <th  valign="bottom"  align="left"><b>TIME</b></th>
	        <th  valign="bottom"  align="left"><b>Title</b></th>
	        <th  valign="bottom"  align="left"><b>Details</b></th>
	        <th  valign="bottom"  align="left"><b>Price</b></th>
	        <th  valign="bottom"  align="left"><b>Contact</b></th>
	    </tr>
	    {% for event in events %}
	    <tr class="{% if event.start_date|date:"l" == 'Friday' or event.start_date|date:"l" == 'Saturday' %}
	    weekend
	    {% elif event.start_date|date:"l" == 'Thursday' %}
	    thursday
	    {% endif %}
	    {% if not event.deposit_date %}
	     prov
	    {% endif %}">
	        <td  valign="top"  align="left">{{ event.start_date }}</td>
	        <td  valign="top"  align="left">{{ event.open_time }}</td>
	        <td  valign="top"  align="left" class="event_title"><a href="/event/{{ event.pk }}"><h3 {% if event.deposit_date %}class="event_title"
                {% else %}class="prov"
                {% endif %}">{{ event.title }}</h3></a></td>
	        <td  valign="top"  align="left">{{ event.details }}</td>
	        <td  valign="top"  align="left">
		    {% if event.is_public == False %}
			    Private
		    {% elif event.door_price < 0 %}
                    Free
            {% elif event.door_price == 0 %}
			    Magic Hat donations
		    {% elif event.door_price == None %}
			    -?-
                    {% else %}
			    £{{ event.door_price }}
		    {% endif %}
		    {% if event.conc_price %}
		        <br />Concs: £{{ event.conc_price }}
		    {% endif %}
		    {% if event.adv_price %}
		        <br />Adv: £{{ event.adv_price }}
		    {% endif %}
	        </td>
	        <td  valign="top"  align="left">{{ event.hirer_name }}</td>
	    </tr>
	{% endfor %}
    </table>
{% endblock %}